# -*- coding: utf-8 -*-
"""pickle_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13yncCtD45Kxj435NTCxYAqDevc89plTJ
"""

# pickle_utils.py
import pickle

def save_to_pickle(obj, filename):
    with open(filename, 'wb') as file:
        pickle.dump(obj, file)

def load_from_pickle(filename):
    with open(filename, 'rb') as file:
        return pickle.load(file)