# -*- coding: utf-8 -*-
"""Poc_reviews.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1321CxRAH0uwtjcvJPmacOc2mePj8jGFk
"""

import streamlit as st
import pandas as pd
import pickle

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder


# Load your trained model
model, data_processing = pickle.load(open('../Reviews_classifier/review_classifier.pkl', 'rb'))

st.title('Reviews Classification Tool')

# File uploader
uploaded_file = st.file_uploader("Choose an Excel file", type=['csv'])
if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)
    X_val=data_processing(df)
    Y_Positive=model.predict(X_val)[:,0]
    Y_Neutral=model.predict(X_val)[:,1]
    Y_Negative=model.predict(X_val)[:,2]
    Y_Irrelevant=model.predict(X_val)[:,3]
    df['Positive'] = Y_Positive
    df['Neutral'] = Y_Neutral
    df['Negative'] = Y_Positive
    df['Irrelevant'] = Y_Irrelevant
    st.write(df_test)







