# -*- coding: utf-8 -*-
"""transformation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/101IJrVP-LOBIVZILgtHNLibzsqGkm5UL
"""

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

def data_processing(df):
  df = df.iloc[:, 2:]
  df.columns = ['label', 'data']
  text=df['data']
  tokenizer = Tokenizer(num_words=10000)
  tokenizer.fit_on_texts(text)
  text = tokenizer.texts_to_sequences(text)
  max_len = 100  # Define the maximum sequence length
  text = pad_sequences(text, maxlen=max_len,padding="post")
  return text